name: Build Windows Application (.EXE)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          npm install

      - name: Build Windows Executables (.EXE)
        run: |
          npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows Executables Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ZeroTrace-Windows-EXE
          path: |
            dist-release/*.exe
          retention-days: 14
